apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\PROGRAMDATA\CHOCOLATEY\lib\kubernetes-kompose\tools\kompose.exe
      --file ../docker-compose-eks.yml convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: config-server
  name: config-server
spec:
  type: NodePort
  ports:
    - port: 8071
      nodePort: 31071
  #- name: "8071"
    #targetPort: 8071
  selector:
    io.kompose.service: config-server
status:
  loadBalancer: {}
